name: raven
description: "News aggregator"
publish_to: 'none'

version: 0.6.0+1

environment:
  sdk: '>=3.2.1 <4.0.0'

dependencies:
  cached_network_image: ^3.3.0
  flutter:
    sdk: flutter

  flutter_html: ^3.0.0-beta.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1
  html: ^0.15.4
  http: ^1.1.2
  intl: ^0.19.0
  share_plus: ^8.0.2
  url_launcher: ^6.2.2

dev_dependencies:
  build_runner: ^2.4.7
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  lints: ^3.0.0
  test: ^1.24.9

flutter:
  uses-material-design: true

